# Generated by Django 4.2.4 on 2023-11-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default='name not given', max_length=20, null=True)),
                ('mother_name', models.CharField(default='name not given', max_length=20, null=True)),
                ('guardian_name', models.CharField(default='name not given', max_length=20, null=True)),
                ('ph1', models.CharField(max_length=10)),
                ('ph2', models.CharField(default='not given', max_length=10, null=True)),
                ('mail1', models.EmailField(max_length=254)),
                ('mail2', models.EmailField(default='second email not available', max_length=254, null=True)),
            ],
        ),
    ]
