# Generated by Django 4.2.4 on 2023-11-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='mail2',
            field=models.EmailField(default='xyz@ght.com', max_length=254, null=True),
        ),
    ]
