# Generated by Django 4.2.4 on 2023-11-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_exam_subject_course_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='english',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='english_out_of',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='listening',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='speaking',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='writing',
        ),
        migrations.AddField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
